name: Primer Components
on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn test
